### ISSUE TITLE
Add a dependency on Alien::Rust so that Makefile.PL doesn't need to check if rustc is available?

### ISSUE THREAD

**Issue by tobyink** [PerlFFI/FFI-Platypus-Lang-Rust#39]
[Alien::Rust](https://metacpan.org/release/ZMUGHAL/Alien-Rust-0.01/view/lib/Alien/Rust.pm)

**Comment by plicease** [comment]
Note to self: will also want to do this for `Test2::Tools::Rustfmt`

**Comment by plicease** [comment]
> ... it's not quite as simple as just the dependency. ...

Just to be clear though, I don't think dependencies of this plugin should need to do anything different though.

**Comment by plicease** [comment]
Implemented in #40, this is on its way to CPAN as 0.14.
